# Generated by Django 5.1.3 on 2025-04-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sysmenu",
            options={"ordering": ["order_num"]},
        ),
        migrations.RemoveField(
            model_name="sysmenu",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="sysmenu",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="sysmenu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="menu.sysmenu",
                verbose_name="父菜单",
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="order_num",
            field=models.IntegerField(default=0, verbose_name="显示顺序"),
        ),
    ]
