# Generated by Django 5.1.3 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_sysmenu_options_remove_sysmenu_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sysmenu",
            name="parent",
        ),
        migrations.AddField(
            model_name="sysmenu",
            name="icon",
            field=models.CharField(max_length=100, null=True, verbose_name="菜单图标"),
        ),
        migrations.AddField(
            model_name="sysmenu",
            name="parent_id",
            field=models.IntegerField(null=True, verbose_name="父菜单ID"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="order_num",
            field=models.IntegerField(null=True, verbose_name="显示顺序"),
        ),
    ]
