# Generated by Django 5.1.3 on 2025-04-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_remove_sysmenu_parent_sysmenu_icon_sysmenu_parent_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sysmenu",
            options={},
        ),
    ]
