# Generated by Django 5.1.3 on 2025-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_sysmenu_options_remove_sysmenu_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysmenu",
            name="icon",
            field=models.CharField(max_length=100, null=True, verbose_name="菜单图标"),
        ),
    ]
