# Generated by Django 5.1.3 on 2025-04-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0008_alter_sysmenu_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysmenu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="menu.sysmenu",
                verbose_name="父菜单",
            ),
        ),
    ]
