# Generated by Django 5.1.3 on 2025-04-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sysuser",
            old_name="avater",
            new_name="avatar",
        ),
    ]
