# Generated by Django 5.1.3 on 2025-05-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_sysuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="avatar",
            field=models.CharField(
                default="https://pub-d470eef1ae124f929afa0d8350e779c7.r2.dev/blog/configs/057c5dd3305a41278d74a7a5c7dffeb5.jpg",
                max_length=255,
                null=True,
                verbose_name="头像",
            ),
        ),
    ]
