# Generated by Django 5.1.3 on 2025-06-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_sysuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="password",
            field=models.CharField(max_length=100, null=True, verbose_name="密码"),
        ),
    ]
