# Generated by Django 5.1.3 on 2025-05-07 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=55, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
                "db_table": "blog_category",
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog_name",
                    models.CharField(
                        default="happYness7", max_length=55, verbose_name="博客名称"
                    ),
                ),
                (
                    "blog_avatar",
                    models.CharField(
                        default="billie.jpg", max_length=255, verbose_name="博客头像"
                    ),
                ),
                (
                    "avatar_bg",
                    models.CharField(
                        max_length=255, null=True, verbose_name="头像背景"
                    ),
                ),
                (
                    "personal_say",
                    models.CharField(
                        max_length=255, null=True, verbose_name="个人签名"
                    ),
                ),
                (
                    "blog_notice",
                    models.CharField(
                        max_length=255, null=True, verbose_name="博客公告"
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0, verbose_name="访问总量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "blog_config",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        max_length=55, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "文章标签",
                "verbose_name_plural": "文章标签",
                "db_table": "blog_tag",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_title",
                    models.CharField(max_length=255, verbose_name="文章标题"),
                ),
                ("article_content", models.TextField(verbose_name="文章内容")),
                (
                    "article_cover",
                    models.CharField(
                        default="billie.jpg", max_length=1234, verbose_name="封面图"
                    ),
                ),
                (
                    "is_top",
                    models.IntegerField(
                        choices=[(1, "置顶"), (2, "不置顶")],
                        default=2,
                        verbose_name="置顶状态",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "公开"), (2, "私密"), (3, "草稿箱")],
                        default=1,
                        verbose_name="文章状态",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "原创"), (2, "转载"), (3, "翻译")],
                        default=1,
                        verbose_name="文章类型",
                    ),
                ),
                (
                    "article_description",
                    models.CharField(max_length=255, verbose_name="文章摘要"),
                ),
                (
                    "order",
                    models.IntegerField(blank=True, null=True, verbose_name="排序权重"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章管理",
                "verbose_name_plural": "文章管理",
                "db_table": "blog_article",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("for_id", models.IntegerField(verbose_name="关联对象ID")),
                (
                    "comment_type",
                    models.IntegerField(
                        choices=[(1, "文章"), (2, "说说"), (3, "留言")],
                        verbose_name="评论类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                ("thumbs_up", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.comment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被回复人",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论管理",
                "verbose_name_plural": "评论管理",
                "db_table": "blog_comment",
            },
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关联时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.article",
                        verbose_name="文章",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章标签关联",
                "verbose_name_plural": "文章标签关联",
                "db_table": "blog_article_tag",
                "unique_together": {("article", "tag")},
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                through="blog.ArticleTag", to="blog.tag", verbose_name="文章标签"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-created_at"], name="create_time_idx"),
        ),
    ]
