# Generated by Django 5.1.3 on 2025-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_author_alter_comment_from_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="article_tags",
                through="blog.ArticleTag",
                to="blog.tag",
                verbose_name="文章标签",
            ),
        ),
    ]
