# Generated by Django 5.1.3 on 2025-05-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_tags"),
        ("user", "0003_alter_sysuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_cover",
            field=models.CharField(max_length=1234, verbose_name="封面图"),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.sysuser",
                verbose_name="作者",
            ),
        ),
    ]
