# Generated by Django 5.1.3 on 2025-05-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_article_cover_alter_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_cover",
            field=models.CharField(
                default="https://pub-d470eef1ae124f929afa0d8350e779c7.r2.dev/blog/article_cover/ff1fe06c6e6947608dcb489277d237d3.jpg",
                max_length=1234,
                verbose_name="封面图",
            ),
        ),
    ]
