# Generated by Django 5.1.3 on 2025-05-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_article_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_name",
                    models.CharField(
                        blank=True, max_length=26, null=True, verbose_name="相册名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=55, null=True, verbose_name="相册描述"
                    ),
                ),
                (
                    "album_cover",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="相册封面"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "相册管理",
                "verbose_name_plural": "相册管理",
                "db_table": "blog_photo_album",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="图片地址"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "正常"), (2, "回收站")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="blog.photoalbum",
                        verbose_name="所属相册",
                    ),
                ),
            ],
            options={
                "verbose_name": "照片管理",
                "verbose_name_plural": "照片管理",
                "db_table": "blog_photo",
                "ordering": ["-created_at"],
            },
        ),
    ]
