# Generated by Django 5.1.3 on 2025-05-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_config_blog_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="git_ee_link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Gitee链接"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="github_link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GitHub链接"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="qq_link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="QQ链接"
            ),
        ),
        migrations.AddField(
            model_name="config",
            name="we_chat_link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="微信链接"
            ),
        ),
    ]
