# Generated by Django 5.1.3 on 2025-05-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_config_git_ee_link_config_github_link_config_qq_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="view_count",
        ),
    ]
