# Generated by Django 5.1.3 on 2025-05-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_config_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="config",
            name="updated_at",
        ),
    ]
