# Generated by Django 5.1.3 on 2025-05-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_config_created_at_remove_config_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="avatar_bg",
        ),
    ]
