# Generated by Django 5.1.3 on 2025-06-09 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_config_avatar_bg"),
        ("user", "0004_alter_sysuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="from_user",
            field=models.ForeignKey(
                default="游客",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_comments",
                to="user.sysuser",
                verbose_name="评论人",
            ),
        ),
    ]
