# Generated by Django 5.1.3 on 2025-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_comment_for_id_alter_comment_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="thumbs_up",
            field=models.IntegerField(default=0, null=True, verbose_name="点赞数"),
        ),
    ]
