# Generated by Django 5.1.3 on 2025-06-09 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_comment_from_user"),
        ("user", "0005_alter_sysuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="from_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_comments",
                to="user.sysuser",
                verbose_name="评论人",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_comments",
                to="user.sysuser",
                verbose_name="被回复人",
            ),
        ),
    ]
