# Generated by Django 5.1.3 on 2025-06-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_comment_from_user_alter_comment_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="for_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="thumbs_up",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="to_user",
        ),
    ]
